version: 2.1
jobs:
  run-test-suite:
    working_directory: ~/gyo-main
    docker:
      - image: circleci/node:10.20.0
    steps:
      - checkout
      - run:
          command: ls -a
      - run:
          command: cd gyo-nuxt
          when: always
      - run:
          command: yarn
          when: always
      - run:
          command: yarn --dev
          when: always
      - run:
          command: yarn test
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports 
workflows:
  test-and-deploy:
    jobs:
    - run-test-suite
