version: 2.1
jobs:
  run-test-suite:
    working_directory: ~/gyo-main/gyo-nuxt
    docker:
      - image: circleci/node:10.20.0
    steps:
      - checkout:
          path: ~/gyo-main
      - run:
          command: yarn
          when: always
      - run:
          command: yarn --dev
          when: always
      - run:
          command: yarn test
workflows:
  test:
    jobs:
    - run-test-suite
