version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1
jobs:
  run-test-suite:
    working_directory: ~/gyo-main/gyo-nuxt
    docker:
      - image: cimg/node:14.15.3-browsers
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 85.0.4183.102
          firefox-version: 80.0.1
      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
          name: Check installed browsers
      - run:
          command: |
            cd ..
            rmdir gyo-nuxt
      - checkout:
          path: ~/gyo-main
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          command: yarn
          when: always
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
              - ~/gyo-main/gyo-nuxt/node_modules
      - run:
          command: |
            cd ~/gyo-main/gyo-nuxt/node_modules
            ls -a
      - run:
          command: yarn --dev
          when: always
      - run:
          command: yarn test
workflows:
  test:
    jobs:
      - run-test-suite
